title: SiteTitle
subtitle: SiteSubtitle
email: email@example.com
description: SiteDescription
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:8080" # the base hostname & protocol for your site, e.g. http://example.com
github_username: githubusername
